/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminInvitation {
  'id' : string,
  'status' : string,
  'createdAt' : Time,
  'whatsapp' : string,
  'email' : string,
  'slack' : string,
  'inviteLink' : string,
  'phone' : string,
  'sentChannels' : Array<string>,
  'telegram' : string,
}
export interface Booking {
  'id' : string,
  'status' : string,
  'createdAt' : Time,
  'user' : Principal,
  'timeSlot' : Time,
}
export type ExternalBlob = Uint8Array;
export interface FileReference {
  'id' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'uploadedAt' : Time,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface LeaderboardEntry {
  'rank' : bigint,
  'user' : Principal,
  'score' : bigint,
}
export interface MembershipTier {
  'id' : string,
  'name' : string,
  'description' : string,
  'benefits' : Array<string>,
  'monthlyFee' : bigint,
  'rewardMultiplier' : bigint,
}
export interface Notification {
  'id' : string,
  'read' : boolean,
  'type' : string,
  'user' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export interface Order {
  'id' : string,
  'status' : string,
  'createdAt' : Time,
  'user' : Principal,
  'totalAmount' : bigint,
  'items' : Array<string>,
}
export interface PointsCategory {
  'id' : string,
  'multiplier' : bigint,
  'name' : string,
  'type' : string,
  'description' : string,
}
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'category' : string,
  'price' : bigint,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface Review {
  'id' : string,
  'createdAt' : Time,
  'user' : Principal,
  'comment' : string,
  'rating' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'loyaltyPoints' : bigint,
  'membershipId' : string,
  'membershipTier' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VenueInfo {
  'hours' : string,
  'faqs' : Array<string>,
  'name' : string,
  'facilities' : Array<string>,
  'location' : string,
  'rules' : Array<string>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addFileReference' : ActorMethod<[ExternalBlob, string], string>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addReview' : ActorMethod<[bigint, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAdminInvitation' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'createAnnouncement' : ActorMethod<[string], undefined>,
  'createBooking' : ActorMethod<[Time], string>,
  'createBookingNotification' : ActorMethod<[string, string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createMembershipTier' : ActorMethod<[MembershipTier], string>,
  'createNotification' : ActorMethod<[Principal, string, string], string>,
  'createOrder' : ActorMethod<[Array<string>, bigint], string>,
  'createPointsCategory' : ActorMethod<[PointsCategory], string>,
  'createSessionReminder' : ActorMethod<[string], undefined>,
  'deleteAllNotifications' : ActorMethod<[], undefined>,
  'deleteMembershipTier' : ActorMethod<[string], undefined>,
  'deleteNotification' : ActorMethod<[string], undefined>,
  'deletePointsCategory' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAdminInvitations' : ActorMethod<[], Array<AdminInvitation>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAvailableTimeSlots' : ActorMethod<[], Array<Time>>,
  'getAwardPointsForPromotionalBookings' : ActorMethod<[], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileReferences' : ActorMethod<[], Array<FileReference>>,
  'getInvitationChannelSuggestions' : ActorMethod<[], Array<string>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMembershipTiers' : ActorMethod<[], Array<MembershipTier>>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getPointsCategories' : ActorMethod<[], Array<PointsCategory>>,
  'getPointsGuide' : ActorMethod<[], string>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVenueInfo' : ActorMethod<[], [] | [VenueInfo]>,
  'getWhatsAppInviteTemplate' : ActorMethod<[], string>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markAllNotificationsAsRead' : ActorMethod<[], undefined>,
  'markNotificationAsRead' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAwardPointsForPromotionalBookings' : ActorMethod<[boolean], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdminInvitationStatus' : ActorMethod<[string, string], undefined>,
  'updateLeaderboardEntry' : ActorMethod<[LeaderboardEntry], undefined>,
  'updateMembershipTier' : ActorMethod<[MembershipTier], undefined>,
  'updatePointsCategory' : ActorMethod<[PointsCategory], undefined>,
  'updatePointsGuide' : ActorMethod<[string], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateVenueInfo' : ActorMethod<[VenueInfo], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];