/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const MembershipTier = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
  'monthlyFee' : IDL.Nat,
  'rewardMultiplier' : IDL.Nat,
});
export const PointsCategory = IDL.Record({
  'id' : IDL.Text,
  'multiplier' : IDL.Nat,
  'name' : IDL.Text,
  'type' : IDL.Text,
  'description' : IDL.Text,
});
export const AdminInvitation = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : Time,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'slack' : IDL.Text,
  'inviteLink' : IDL.Text,
  'phone' : IDL.Text,
  'sentChannels' : IDL.Vec(IDL.Text),
  'telegram' : IDL.Text,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const TimeSlot = IDL.Record({
  'startTime' : Time,
  'duration' : IDL.Nat,
  'isLive' : IDL.Bool,
  'isEnabled' : IDL.Bool,
});
export const BusinessContactInfo = IDL.Record({
  'description' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'loyaltyPoints' : IDL.Nat,
  'membershipId' : IDL.Text,
  'membershipTier' : IDL.Text,
});
export const FileReference = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'uploadedAt' : Time,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const LeaderboardEntry = IDL.Record({
  'rank' : IDL.Nat,
  'user' : IDL.Principal,
  'score' : IDL.Nat,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'timeSlot' : Time,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'read' : IDL.Bool,
  'type' : IDL.Text,
  'user' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(IDL.Text),
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const VenueInfo = IDL.Record({
  'hours' : IDL.Text,
  'faqs' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'facilities' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'rules' : IDL.Vec(IDL.Text),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addFileReference' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Text], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addReview' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkSetTimeSlotStates' : IDL.Func(
      [IDL.Vec(IDL.Tuple(Time, IDL.Bool, IDL.Bool))],
      [],
      [],
    ),
  'createAdminInvitation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createAnnouncement' : IDL.Func([IDL.Text], [], []),
  'createBooking' : IDL.Func([Time], [IDL.Text], []),
  'createBookingNotification' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createMembershipTier' : IDL.Func([MembershipTier], [IDL.Text], []),
  'createNotification' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func([IDL.Vec(IDL.Text), IDL.Nat], [IDL.Text], []),
  'createPointsCategory' : IDL.Func([PointsCategory], [IDL.Text], []),
  'createSessionReminder' : IDL.Func([IDL.Text], [], []),
  'createTimeSlot' : IDL.Func([Time, IDL.Nat], [], []),
  'deleteAllNotifications' : IDL.Func([], [], []),
  'deleteMembershipTier' : IDL.Func([IDL.Text], [], []),
  'deleteNotification' : IDL.Func([IDL.Text], [], []),
  'deletePointsCategory' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'extendBooking15Minutes' : IDL.Func([IDL.Text], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAdminInvitations' : IDL.Func([], [IDL.Vec(AdminInvitation)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
  'getAvailableTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
  'getAwardPointsForPromotionalBookings' : IDL.Func([], [IDL.Bool], ['query']),
  'getBusinessContactInfo' : IDL.Func(
      [],
      [IDL.Opt(BusinessContactInfo)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'getInvitationChannelSuggestions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMembershipTiers' : IDL.Func([], [IDL.Vec(MembershipTier)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPointsCategories' : IDL.Func([], [IDL.Vec(PointsCategory)], ['query']),
  'getPointsGuide' : IDL.Func([], [IDL.Text], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVenueInfo' : IDL.Func([], [IDL.Opt(VenueInfo)], ['query']),
  'getWhatsAppInviteTemplate' : IDL.Func([], [IDL.Text], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsAsRead' : IDL.Func([], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAwardPointsForPromotionalBookings' : IDL.Func([IDL.Bool], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'toggleTimeSlotAvailability' : IDL.Func([Time], [], []),
  'toggleTimeSlotLiveStatus' : IDL.Func([Time], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAdminInvitationStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateBusinessContactInfo' : IDL.Func([BusinessContactInfo], [], []),
  'updateLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
  'updateMembershipTier' : IDL.Func([MembershipTier], [], []),
  'updatePointsCategory' : IDL.Func([PointsCategory], [], []),
  'updatePointsGuide' : IDL.Func([IDL.Text], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateTimeSlot' : IDL.Func([Time, IDL.Nat], [], []),
  'updateVenueInfo' : IDL.Func([VenueInfo], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const MembershipTier = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
    'monthlyFee' : IDL.Nat,
    'rewardMultiplier' : IDL.Nat,
  });
  const PointsCategory = IDL.Record({
    'id' : IDL.Text,
    'multiplier' : IDL.Nat,
    'name' : IDL.Text,
    'type' : IDL.Text,
    'description' : IDL.Text,
  });
  const AdminInvitation = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : Time,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'slack' : IDL.Text,
    'inviteLink' : IDL.Text,
    'phone' : IDL.Text,
    'sentChannels' : IDL.Vec(IDL.Text),
    'telegram' : IDL.Text,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const TimeSlot = IDL.Record({
    'startTime' : Time,
    'duration' : IDL.Nat,
    'isLive' : IDL.Bool,
    'isEnabled' : IDL.Bool,
  });
  const BusinessContactInfo = IDL.Record({
    'description' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'loyaltyPoints' : IDL.Nat,
    'membershipId' : IDL.Text,
    'membershipTier' : IDL.Text,
  });
  const FileReference = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'uploadedAt' : Time,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const LeaderboardEntry = IDL.Record({
    'rank' : IDL.Nat,
    'user' : IDL.Principal,
    'score' : IDL.Nat,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'timeSlot' : Time,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'read' : IDL.Bool,
    'type' : IDL.Text,
    'user' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(IDL.Text),
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const VenueInfo = IDL.Record({
    'hours' : IDL.Text,
    'faqs' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'facilities' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'rules' : IDL.Vec(IDL.Text),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addFileReference' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Text], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addReview' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkSetTimeSlotStates' : IDL.Func(
        [IDL.Vec(IDL.Tuple(Time, IDL.Bool, IDL.Bool))],
        [],
        [],
      ),
    'createAdminInvitation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createAnnouncement' : IDL.Func([IDL.Text], [], []),
    'createBooking' : IDL.Func([Time], [IDL.Text], []),
    'createBookingNotification' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createMembershipTier' : IDL.Func([MembershipTier], [IDL.Text], []),
    'createNotification' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func([IDL.Vec(IDL.Text), IDL.Nat], [IDL.Text], []),
    'createPointsCategory' : IDL.Func([PointsCategory], [IDL.Text], []),
    'createSessionReminder' : IDL.Func([IDL.Text], [], []),
    'createTimeSlot' : IDL.Func([Time, IDL.Nat], [], []),
    'deleteAllNotifications' : IDL.Func([], [], []),
    'deleteMembershipTier' : IDL.Func([IDL.Text], [], []),
    'deleteNotification' : IDL.Func([IDL.Text], [], []),
    'deletePointsCategory' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'extendBooking15Minutes' : IDL.Func([IDL.Text], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAdminInvitations' : IDL.Func([], [IDL.Vec(AdminInvitation)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
    'getAvailableTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
    'getAwardPointsForPromotionalBookings' : IDL.Func(
        [],
        [IDL.Bool],
        ['query'],
      ),
    'getBusinessContactInfo' : IDL.Func(
        [],
        [IDL.Opt(BusinessContactInfo)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'getInvitationChannelSuggestions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMembershipTiers' : IDL.Func([], [IDL.Vec(MembershipTier)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPointsCategories' : IDL.Func([], [IDL.Vec(PointsCategory)], ['query']),
    'getPointsGuide' : IDL.Func([], [IDL.Text], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVenueInfo' : IDL.Func([], [IDL.Opt(VenueInfo)], ['query']),
    'getWhatsAppInviteTemplate' : IDL.Func([], [IDL.Text], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsAsRead' : IDL.Func([], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAwardPointsForPromotionalBookings' : IDL.Func([IDL.Bool], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'toggleTimeSlotAvailability' : IDL.Func([Time], [], []),
    'toggleTimeSlotLiveStatus' : IDL.Func([Time], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAdminInvitationStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateBusinessContactInfo' : IDL.Func([BusinessContactInfo], [], []),
    'updateLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
    'updateMembershipTier' : IDL.Func([MembershipTier], [], []),
    'updatePointsCategory' : IDL.Func([PointsCategory], [], []),
    'updatePointsGuide' : IDL.Func([IDL.Text], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateTimeSlot' : IDL.Func([Time, IDL.Nat], [], []),
    'updateVenueInfo' : IDL.Func([VenueInfo], [], []),
  });
};

export const init = ({ IDL }) => { return []; };